services:
  mlflow:
    build:
      context: .
      dockerfile: src/mlflow-server/Dockerfile
    container_name: mlflow
    ports:
      - "5050:5050"
    volumes:
      # Persist experiment metadata and artifacts on host
      - ./mlruns:/mlflow/mlruns
      - ./mlflow.db:/mlflow/mlflow.db
    networks:
      - mlops-net

  training_api:
    build:
      context: .
      dockerfile: src/training_api/Dockerfile
    container_name: taxi-api
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:3030
      - MODEL_NAME=nyc_taxi_duration
      - MODEL_ALIAS=production
    ports:
      - "8080:8080"
    depends_on:
      - mlflow
    networks:
      - mlops-net

networks:
  mlops-net:
    driver: bridge