artifact_location: /home/g512/Documents/Uni/Masters/2nd/1st/LIA/downtown-cab-co/qweq/0
creation_time: 1764636468942
experiment_id: '0'
last_update_time: 1764636468942
lifecycle_stage: active
name: Default
